<?php 
/**
 * Virtina
 * @package    Virtina_Bestseller
 * @copyright  Copyright (c) 2015-2016 Virtina. (http://www.virtina.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $this->getProducts() ?>
<?php $configSlider = Mage::getStoreConfig('bestseller/slider/infinite'); ?>
<?php $configImgsize = Mage::getStoreConfig('bestseller/slider/imgsize'); ?>
<?php $configSpeed = Mage::getStoreConfig('bestseller/slider/speed'); ?>
<?php $configAuto = Mage::getStoreConfig('bestseller/slider/auto'); ?>
<?php $configNumber = Mage::getStoreConfig('bestseller/slider/number'); ?>
<?php $configScroll = Mage::getStoreConfig('bestseller/slider/scroll'); ?>
<?php if ($configSlider) { ?>		<!-- If slider is enabled -->
	<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
	<div class="widget widget-new-products bestseller">
		<div class="widget-title">
			<h2><?php echo $this->__('Best Selling Products') ?></h2>
		</div>
		<div class="widget-products" >
			<?php echo $this->getPagerHtml() ?>
			<?php $_columnCount = 5; ?>
			<?php $i=0; ?>
			<ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col-widget" id ="bestProdCar">
				<?php foreach ($_products->getItems() as $_product): ?>
					<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
						<?php $_imgSize = $configImgsize; ?>

						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
						</a>
						<div class="product-info">
							<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
							<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>                                     
						</div>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
	<?php endif; ?>
<?php } else { ?>		<!-- If slider is disabled -->
	<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
	<div class="widget widget-new-products bestseller">
		<div class="widget-title">
			<h2><?php echo $this->__('Best Selling Products') ?></h2>
		</div>
		<div class="widget-products" >
			<?php echo $this->getPagerHtml() ?>
			<?php $_columnCount = 5; ?>
			<?php $i=0; ?>
			<ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col-widget" >
				<?php foreach ($_products->getItems() as $_product): ?>
					<li class="item<?php if($i==0): ?> first<?php elseif($i==($_columnCount-1)): ?> last<?php endif; ?>">
						<?php $_imgSize = $configImgsize; ?>

						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
						</a>
						<div class="product-info">
							<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
							<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>                                     
						</div>
					</li>
				    <?php
					  if(++$i >= 6)
						 break;
				    ?>					
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
	<?php endif; ?>	
	
<?php }  ?>

<script type="text/javascript">	
jQuery(document).ready(function(){
	jQuery('#bestProdCar').slick({
	  dots: false,
	  infinite: true,
	  speed: <?php echo $configSpeed?$configSpeed:'1000'; ?>,
	  slidesToShow: <?php echo $configNumber?$configNumber:'5'; ?>,
	  slidesToScroll: <?php echo $configScroll?$configScroll:'1'; ?>,
	  autoplay : <?php echo $configAuto?'true':'false' ;?>,
	  prevArrow:'<img src="<?php echo $this->getSkinUrl('images/bestseller/previous.png') ?>" data-role="none" class="slick-prev" aria-label="Previous" tabindex="0" width="20" height="20">',
	  nextArrow:'<img src="<?php echo $this->getSkinUrl('images/bestseller/next.png') ?>" data-role="none" class="slick-next" aria-label="Next" tabindex="0" width="20" height="20">',
	  responsive: [
		{
		  breakpoint: 1024,
		  settings: {
			slidesToShow: 4,
			slidesToScroll: <?php echo $configScroll?$configScroll:'1'; ?>,
			infinite: true,
			dots: true
		  }
		},
		{
		  breakpoint: 600,
		  settings: {
			slidesToShow: 2,
			slidesToScroll: <?php echo $configScroll?$configScroll:'1'; ?>
		  }
		},
		{
		  breakpoint: 480,
		  settings: {
			slidesToShow: 1,
			slidesToScroll: 1
		  }
		}
	  ]
	});
});
</script>
